<?php
namespace backend\controllers;

use common\models\LoginForm;
use common\models\User;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use Yii;

/**
 * Site controller.
 * It is responsible for displaying static pages, and logging users in and out.
 */
class SiteController extends BackendController
{
    public function beforeAction($action)
    {
        if ($action->id == 'login' || $action->id == 'logout')
            $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * Returns a list of behaviors that this component should behave as.
     *
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Declares external actions for the controller.
     *
     * @return array
     */
    public function actions()
    { 
        
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays the index (home) page.
     * Use it in case your home page contains static content.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in the user if his account is activated,
     * if not, displays standard error message.
     *
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        $this->layout = 'authorization';
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }



        // if (!Yii::$app->user->isGuest) 
        // {
        //     return $this->goHome();
        // }

        // // get setting value for 'Login With Email'
        // $lwe = Yii::$app->params['lwe'];

        // // if 'lwe' value is 'true' we instantiate LoginForm in 'lwe' scenario
        // $model = $lwe ? new LoginForm(['scenario' => 'lwe']) : new LoginForm();

        // // now we can try to log in the user
        // if ($model->load(Yii::$app->request->post()) && $model->login()) 
        // {
        //     return $this->goBack();
        // }
        // // user couldn't be logged in, because he has not activated his account
        // elseif($model->notActivated())
        // {
        //     // if his account is not activated, he will have to activate it first
        //     Yii::$app->session->setFlash('error', 
        //         'You have to activate your account first. Please check your email.');

        //     return $this->refresh();
        // }    
        // // account is activated, but some other errors have happened
        // else
        // {
        //     return $this->render('login', [
        //         'model' => $model,
        //     ]);
        // }
    }

    /**
     * Logs out the user.
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}
